sun_sar9b_sky130nm:
  remote: git@github.com:wulffern/sun_sar9b_sky130nm.git
  revision: main

#- Carsten's PDK. Borders, symbols, loop stability
cpdk:
  remote: git@github.com:wulffern/cpdk.git
  revision: main

#- Transistor library (sky130B,sch,lay)
sun_tr_sky130nm:
  remote: git@github.com:wulffern/sun_tr_sky130nm.git
  revision: main

#- Transistor library (sky130B,sch,lay)
sun_trb_sky130nm:
  remote: git@github.com:wulffern/sun_trb_sky130nm.git
  revision: main

#- Technology used by sun/rply/cnr projects
tech_sky130B:
  remote: git@github.com:wulffern/tech_sky130B.git
  revision: main

